config/routes.rb
Divelogs::Application.routes.draw do
  get "pages/info"
  root to: redirect('/divelogs')
  resources :divelogs

end

app/models/divelog.rb
class Divelog < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	geocoded_by :point
    after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/divelogs_controller.rb
class DivelogsController < ApplicationController
  before_action :set_divelog, only: [:show, :edit, :update, :destroy]

  # GET /divelogs
  # GET /divelogs.json
  def index
    @divelogs = Divelog.all
  end

  # GET /divelogs/1
  # GET /divelogs/1.json
  def show
    @divelogs = Divelog.all
    @hash = Gmaps4rails.build_markers(@divelogs) do |divelog, marker|
      marker.lat divelog.latitude
      marker.lng divelog.longitude
      marker.infowindow divelog.point
    end  
  end

  # GET /divelogs/new
  def new
    @divelog = Divelog.new
  end

  # GET /divelogs/1/edit
  def edit
  end

  # POST /divelogs
  # POST /divelogs.json
  def create
    @divelog = Divelog.new(divelog_params)

    respond_to do |format|
      if @divelog.save
        format.html { redirect_to @divelog, notice: 'Divelog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @divelog }
      else
        format.html { render action: 'new' }
        format.json { render json: @divelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divelogs/1
  # PATCH/PUT /divelogs/1.json
  def update
    respond_to do |format|
      if @divelog.update(divelog_params)
        format.html { redirect_to @divelog, notice: 'Divelog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @divelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divelogs/1
  # DELETE /divelogs/1.json
  def destroy
    @divelog.destroy
    respond_to do |format|
      format.html { redirect_to divelogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_divelog
      @divelog = Divelog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def divelog_params
      params.require(:divelog).permit(:date, :point, :description, :picture, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divelogs_helper.rb
module DivelogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/divelogs/_form.html.erb
<%= form_for @divelog, :html => {:multipart => true} do |f| %>
  <% if @divelog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@divelog.errors.count, "error") %> prohibited this divelog from being saved:</h2>

      <ul>
      <% @divelog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :point %><br>
    <%= f.text_field :point %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divelogs/edit.html.erb
<h1>Editing divelog</h1>

<%= render 'form' %>

<%= link_to 'Show', @divelog %> |
<%= link_to 'Back', divelogs_path %>

app/views/divelogs/index.html.erb
<h1>Listing Divelogs</h1>

<% @divelogs.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |divelog| %>
      <div class="span4">
        <%= image_tag divelog.picture_url, :width => '100%' if divelog.picture.present?%>
        <h4><%= link_to divelog.point, divelog %></h4>
        <%= divelog.description %>
      </div>
    <% end %>
  </div>
<% end %>
<!--
  <tbody>
    <% @divelogs.each do |divelog| %>
      <tr>
        <td><%= divelog.date %></td>
        <td><%= divelog.point %></td>
        <td><%= divelog.description %></td>
        <td><%= divelog.picture %></td>
        <td><%= divelog.latitude %></td>
        <td><%= divelog.longitude %></td>
        <td><%= link_to 'Show', divelog %></td>
        <td><%= link_to 'Edit', edit_divelog_path(divelog) %></td>
        <td><%= link_to 'Destroy', divelog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>

<%= link_to 'New Divelog', new_divelog_path %>

app/views/divelogs/new.html.erb
<h1>New divelog</h1>

<%= render 'form' %>

<%= link_to 'Back', divelogs_path %>

app/views/divelogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span6">
    <%= image_tag(@divelog.picture_url, :width => "95%") if @divelog.picture.present? %>
  </div>

  <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: {id: 'pointmap'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
      });
  </script>

  <div style='width: 600px;'>
    <div id="pointmap" style='width: 600px; height: 300px;'></div>
  </div>

  <div class="span3">
    <p><b>Point: </b><%= @divelog.point %></p>
    <p><b>Description: </b><%= @divelog.description %></p>
    <p><b>Date: </b><%= @divelog.date %></p>
    <p><b>Latitude: </b><%= @divelog.latitude %></p><p><b>Longitude: </b><%= @divelog.longitude %></p>
    <p>
      <%= link_to 'Edit', edit_divelog_path(@divelog) %> |
      <%= link_to 'Destroy', @divelog, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', divelogs_path %>
    </p>
  </div>
</div>


<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @divelog.date %>
</p>

<p>
  <strong>Point:</strong>
  <%= @divelog.point %>
</p>

<p>
  <strong>Description:</strong>
  <%= @divelog.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@divelog.picture_url, width: 600) if @divelog.picture.present? %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @divelog.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @divelog.longitude %>
</p>

<%= link_to 'Edit', edit_divelog_path(@divelog) %> |
<%= link_to 'Back', divelogs_path %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Divelogs</title>
  <!--<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />-->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css">

  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Diving app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/divelogs">Divelogs</a></li>
        <li ><%= link_to 'New Log', new_divelog_path %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript">
  </script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'>
  </script>
</div>
<footer>
  <div class="container">
    whitechip 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>

<h2>https://github.com/whitechip/</h2>

<p>Find me in app/views/pages/info.html.erb</p>